"""AMPMotionLoader: expert (s, s') samples for AMP discriminators.

Framework-independent (plain numpy/torch on precomputed `.npz` motion data -- no forward
kinematics, no mjlab imports). Quaternions are normalized on load and `projected_gravity`
is recomputed from them (see `_load_data`). Forward kinematics and velocities are computed
offline by `scripts/motion/replay_motions.py` and baked into the `.npz` files.
"""

from __future__ import annotations

import copy
import os
from typing import Generator, List, Tuple

import numpy as np
import torch


def _quat_apply_inverse(q: np.ndarray, v: np.ndarray) -> np.ndarray:
    """Rotate world vector(s) `v` into the frame of unit quaternion(s) `q` (w, x, y, z)."""
    w, xyz = q[..., :1], -q[..., 1:]
    xyz, v = np.broadcast_arrays(xyz, v)
    t = 2.0 * np.cross(xyz, v)
    return v + w * t + np.cross(xyz, t)


class AMPMotionLoader:
    """Loads motions generated by an offline retargeting/FK script.

    Expects the input data to already be interpolated to the simulation frequency
    and the joints/bodies to be named consistently with the simulated robot (order
    need not match -- selection is by name).
    """

    def __init__(
        self,
        device: str,
        motion_directory: str,
        motion_names: List[str],
        motion_weights: List[float],
        root_body_name: str,
        selected_obs_names: List[str],
        selected_body_names: List[str] | None = None,
        selected_joint_names: List[str] | None = None,
    ):
        self.device = device
        self.root_body_name = root_body_name
        self.motion_directory = motion_directory
        self.motion_names = motion_names

        if selected_body_names is None:
            motion = np.load(os.path.join(motion_directory, f"{motion_names[0]}.npz"), allow_pickle=True)
            selected_body_names = motion["body_names"]
        if selected_joint_names is None:
            motion = np.load(os.path.join(motion_directory, f"{motion_names[0]}.npz"), allow_pickle=True)
            selected_joint_names = motion["joint_names"]
        self.selected_body_names = selected_body_names
        self.selected_joint_names = selected_joint_names

        # Raw joint order the motion files store joint_pos/joint_vel in (set by
        # _load_data). reset_states is built from this order until
        # remap_reset_joint_order() reindexes it into the simulated robot's DOF order.
        self.reset_joint_names: List[str] | None = None
        self._reset_remapped = False

        obs_motions, next_obs_motions, reset_states, motion_length = [], [], [], []
        for motion_name in motion_names:
            motion_path = os.path.join(motion_directory, f"{motion_name}.npz")
            obs_motion, next_obs_motion, reset_state = self._load_data(
                motion_path, selected_obs_names, selected_body_names, selected_joint_names
            )
            obs_motions.append(obs_motion)
            next_obs_motions.append(next_obs_motion)
            reset_states.append(reset_state)
            motion_length.append(obs_motion.shape[0])
            print(f"[AMPMotionLoader] Loaded Motion {motion_name} with {obs_motion.shape[0]} frames")
        print(f"[AMPMotionLoader] Finished loading {len(motion_names)} motions")

        self.obs_motions = torch.cat(obs_motions, dim=0)
        self.next_obs_motions = torch.cat(next_obs_motions, dim=0)
        self.reset_states = torch.cat(reset_states, dim=0)

        weights = torch.tensor(motion_weights, dtype=torch.float32, device=self.device)
        self.motion_weights = weights / weights.sum()

        per_frame = torch.cat(
            [torch.full((L,), w / L, device=self.device) for w, L in zip(self.motion_weights, motion_length)]
        )
        self.per_frame_weights = per_frame / per_frame.sum()

    def mini_batch_generator(
        self, num_mini_batch: int, mini_batch_size: int
    ) -> Generator[Tuple[torch.Tensor, torch.Tensor], None, None]:
        """Yield (state, next_state) pairs sampled directly from the precomputed buffers."""
        for _ in range(num_mini_batch):
            idx = torch.multinomial(self.per_frame_weights, mini_batch_size, replacement=True)
            yield self.obs_motions[idx], self.next_obs_motions[idx]

    feed_forward_generator = mini_batch_generator

    def get_state_for_reset(self, number_of_samples: int) -> torch.Tensor:
        """Random full states for RSI env resets: [quat(4), lin_vel(3), ang_vel(3), joint_pos, joint_vel]."""
        idx = torch.multinomial(self.per_frame_weights, number_of_samples, replacement=True)
        return self.reset_states[idx]

    def remap_reset_joint_order(self, target_joint_names: List[str]) -> None:
        """Reindex reset_states' joint_pos/joint_vel block into `target_joint_names` order."""
        if self._reset_remapped:
            return
        assert self.reset_joint_names is not None, "No motion files have been loaded yet."
        missing = set(self.reset_joint_names) - set(target_joint_names)
        assert not missing, f"[AMPMotionLoader] motion files reference joints not found on the robot: {missing}"
        missing = set(target_joint_names) - set(self.reset_joint_names)
        assert not missing, f"[AMPMotionLoader] robot has joints missing from the motion files: {missing}"

        ids = [self.reset_joint_names.index(name) for name in target_joint_names]
        num_dof = len(self.reset_joint_names)
        root_state = self.reset_states[:, :10]
        joint_pos = self.reset_states[:, 10 : 10 + num_dof][:, ids]
        joint_vel = self.reset_states[:, 10 + num_dof : 10 + 2 * num_dof][:, ids]
        self.reset_states = torch.cat([root_state, joint_pos, joint_vel], dim=-1)
        self.reset_joint_names = list(target_joint_names)
        self._reset_remapped = True

    def _load_data(self, motion_path, selected_obs_names, selected_body_names, selected_joint_names):
        raw = np.load(motion_path, allow_pickle=True)
        joint_names = raw["joint_names"].tolist()
        body_names = raw["body_names"].tolist()

        if self.reset_joint_names is None:
            self.reset_joint_names = joint_names
        else:
            assert self.reset_joint_names == joint_names, (
                f"[AMPMotionLoader] raw joint order in {motion_path} differs from earlier-loaded "
                f"motion files. Expected: {self.reset_joint_names}, got: {joint_names}"
            )

        motion = copy.deepcopy({key: raw[key] for key in raw.files})

        # The retargeting output's quaternions are not unit length (run clips reach
        # |q| ~1.2, likely lerp resampling), and every root-frame field was rotated with
        # those un-normalized quats -- which scales vectors by |q|^2 (projected_gravity
        # up to 1.2, body velocities off by up to ~4 m/s). The simulated robot's
        # features are exact, so the discriminator could separate expert from policy on
        # that alone. Normalize the quats and recompute the root-frame fields from the
        # world-frame ones, using the same definitions as the sim-side observations
        # (`link_pos_b`/`link_lin_vel_b`/`link_ang_vel_b`, `projected_gravity`). On the
        # few frames where |q| is already ~1 this reproduces the stored values.
        for k in ("body_quat_w", "body_quat_b"):
            motion[k] = motion[k] / np.linalg.norm(motion[k], axis=-1, keepdims=True)

        root_body_id = body_names.index(self.root_body_name)
        root_quat_w = motion["body_quat_w"][:, root_body_id]
        root_q = root_quat_w[:, None]
        root_pos_w = motion["body_pos_w"][:, root_body_id : root_body_id + 1]
        motion["body_pos_b"] = _quat_apply_inverse(root_q, motion["body_pos_w"] - root_pos_w)
        motion["body_lin_vel_b"] = _quat_apply_inverse(root_q, motion["body_lin_vel_w"])
        motion["body_ang_vel_b"] = _quat_apply_inverse(root_q, motion["body_ang_vel_w"])
        motion["projected_gravity"] = _quat_apply_inverse(root_quat_w, np.array([0.0, 0.0, -1.0]))

        # Root state, derived from the root body's selection out of the body-keyed fields.
        for k in ("body_pos_w", "body_quat_w", "body_lin_vel_w", "body_ang_vel_w", "body_lin_vel_b", "body_ang_vel_b"):
            motion[f"root_{k[5:]}"] = motion[k][:, root_body_id]

        obs_names = list(motion.keys())
        assert set(selected_joint_names).issubset(set(joint_names)), (
            f"[AMPMotionLoader] joint mismatch in file {motion_path}, available: {joint_names}"
        )
        assert set(selected_body_names).issubset(set(body_names)), (
            f"[AMPMotionLoader] body mismatch in file {motion_path}, available: {body_names}"
        )
        assert set(selected_obs_names).issubset(set(obs_names)), (
            f"[AMPMotionLoader] observation mismatch in file {motion_path}, available: {obs_names}"
        )

        joint_ids = [joint_names.index(item) for item in selected_joint_names]
        for k in ("joint_pos", "joint_vel"):
            motion[k] = motion[k][:, joint_ids]

        body_ids = [body_names.index(item) for item in selected_body_names]
        for k in (
            "body_pos_w", "body_quat_w", "body_lin_vel_w", "body_ang_vel_w",
            "body_pos_b", "body_quat_b", "body_lin_vel_b", "body_ang_vel_b",
        ):
            motion[k] = motion[k][:, body_ids]

        obs_motion = np.concatenate(
            [motion[name].reshape(motion[name].shape[0], -1) for name in selected_obs_names], axis=-1
        )
        obs_motion = torch.tensor(obs_motion, device=self.device, dtype=torch.float32)

        # Next-observation, assuming the file is already sampled to sim dt.
        next_obs_motion = torch.cat([obs_motion[1:], obs_motion[None, -1]], dim=0)

        reset_state = np.concatenate(
            [
                root_quat_w,
                raw["body_lin_vel_w"][:, root_body_id],
                raw["body_ang_vel_w"][:, root_body_id],
                raw["joint_pos"],
                raw["joint_vel"],
            ],
            axis=-1,
        )
        reset_state = torch.tensor(reset_state, device=self.device, dtype=torch.float32)

        return obs_motion, next_obs_motion, reset_state

    @property
    def observation_dim(self) -> int:
        return self.obs_motions.shape[-1]

    @property
    def num_motions(self) -> int:
        return len(self.motion_names)
